CREATE TABLE IF NOT EXISTS tb_ai_generation_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL,
    workspace_id BIGINT NOT NULL,
    requirement_title VARCHAR(255) NOT NULL,
    requirement_content TEXT NOT NULL,
    output_mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    current_step INT NOT NULL DEFAULT 1,
    step_message VARCHAR(500),
    error_message TEXT,
    directory_id BIGINT,
    directory_name VARCHAR(500),
    provider VARCHAR(64),
    model VARCHAR(128),
    asset_ids_json TEXT,
    warnings_json TEXT,
    invalid_cases_json TEXT,
    generated_cases_json TEXT,
    review_result_json TEXT,
    adopted_case_indexes_json TEXT,
    deleted_case_indexes_json TEXT,
    saved_case_count INT NOT NULL DEFAULT 0,
    generated_count INT NOT NULL DEFAULT 0,
    cancel_requested TINYINT NOT NULL DEFAULT 0,
    source_task_id VARCHAR(64),
    finished_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ai_generation_task_task_id (task_id),
    KEY idx_ai_generation_task_workspace_id (workspace_id),
    KEY idx_ai_generation_task_status (status)
);
